function openForm(type,id){const map={task:'tasks',goal:'goals',project:'projects',deadline:'deadlines',note:'notes',document:'documents'},key=map[type],x=id?db[key].find(a=>a.id===id):null,A=AREAS.map(a=>'<option value="'+esc(a)+'" '+(x?.area===a?'selected':'')+'>'+esc(a)+'</option>').join('');let h='';
if(type==='task')h='<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field"><label>Area</label><select name="area">'+A+'</select></div><div class="field"><label>Priority</label><select name="priority">'+['Low','Medium','High','Urgent'].map(v=>'<option '+(x?.priority===v?'selected':'')+'>'+v+'</option>').join('')+'</select></div><div class="field"><label>Status</label><select name="status">'+['Not Started','In Progress','Completed'].map(v=>'<option '+(x?.status===v?'selected':'')+'>'+v+'</option>').join('')+'</select></div><div class="field"><label>Due</label><input type="date" name="due" value="'+(x?.due||'')+'"></div></div>';
if(type==='goal')h='<div class="formgrid"><div class="field full"><label>Goal</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field"><label>Area</label><select name="area">'+A+'</select></div><div class="field"><label>Target</label><input type="date" name="target" value="'+(x?.target||'')+'"></div><div class="field"><label>Progress %</label><input type="number" min="0" max="100" name="progress" value="'+(x?.progress||0)+'"></div><div class="field"><label>Status</label><select name="status"><option>Active</option><option>Completed</option><option>Paused</option></select></div></div>';
if(type==='project')h='<div class="formgrid"><div class="field full"><label>Project</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field"><label>Area</label><select name="area">'+A+'</select></div><div class="field"><label>Status</label><select name="status"><option>Planning</option><option>Active</option><option>On Hold</option><option>Completed</option></select></div><div class="field"><label>Priority</label><select name="priority"><option>Low</option><option>Medium</option><option>High</option></select></div><div class="field"><label>Progress %</label><input type="number" min="0" max="100" name="progress" value="'+(x?.progress||0)+'"></div><div class="field"><label>Deadline</label><input type="date" name="deadline" value="'+(x?.deadline||'')+'"></div><div class="field full"><label>Description</label><textarea name="description">'+esc(x?.description||'')+'</textarea></div></div>';
if(type==='deadline')h='<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field"><label>Date</label><input type="date" name="date" required value="'+(x?.date||'')+'"></div><div class="field"><label>Time</label><input type="time" name="time" value="'+(x?.time||'')+'"></div><div class="field"><label>Area</label><select name="area">'+A+'</select></div><div class="field"><label>Priority</label><select name="priority"><option>Low</option><option>Medium</option><option>High</option></select></div></div>';
if(type==='note')h='<div class="formgrid"><div class="field full"><label>Title</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field full"><label>Content</label><textarea name="content">'+esc(x?.content||'')+'</textarea></div></div>';
if(type==='document')h='<div class="formgrid"><div class="field full"><label>Document name</label><input name="title" required value="'+esc(x?.title||'')+'"></div><div class="field"><label>Type</label><input name="type" value="'+esc(x?.type||'Report')+'"></div><div class="field"><label>Area</label><select name="area">'+A+'</select></div><div class="field"><label>Status</label><select name="status"><option>Planned</option><option>In Progress</option><option>Completed</option></select></div></div>';
$('modalTitle').textContent=(id?'Edit ':'Add ')+type;$('form').innerHTML=h+'<div class="tools" style="justify-content:flex-end;margin-top:16px"><button type="button" class="btn" onclick="closeModal()">Cancel</button><button class="btn primary">Save</button></div>';$('form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());if(d.progress!==undefined)d.progress=Math.max(0,Math.min(100,Number(d.progress)));if(id)Object.assign(db[key].find(a=>a.id===id),d);else{d.id=Date.now();db[key].push(d)}save();closeModal();render();toast(type+' saved')};$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}function removeItem(k,id){if(confirm('Delete this item?')){db[k]=db[k].filter(x=>x.id!==id);save();render();toast('Deleted')}}
function saveProfile(){const n=$('name').value.trim()||'Abraham Waar';localStorage.setItem('profileName',n);$('profileName').textContent=n;$('avatar').textContent=n[0].toUpperCase();toast('Profile saved')}
function toggleTheme(){const d=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=d;localStorage.setItem('theme',d)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='my-life-dashboard-data.json';a.click()}
function resetData(){if(confirm('Reset all dashboard data?')){db=structuredClone(SEED);save();render();toast('Dashboard reset')}}
async function configureCloud(){const u=$('sbUrl').value.trim(),k=$('sbKey').value.trim();localStorage.setItem('sbUrl',u);localStorage.setItem('sbKey',k);if(window.supabase&&u&&k){cloud=window.supabase.createClient(u,k);toast('Cloud connection saved')}else toast('Enter a valid URL and anon/publishable key')}
async function cloudSave(){if(!cloud)return;const s=await cloud.auth.getSession();if(s.data.session)await cloud.from('life_dashboard').upsert({user_id:s.data.session.user.id,data:db,updated_at:new Date().toISOString()})}
async function loginCloud(){if(!cloud)await configureCloud();if(!cloud)return;const email=prompt('Email');if(!email)return;const password=prompt('Password (minimum 6 characters)');if(!password)return;let r=await cloud.auth.signInWithPassword({email,password});if(r.error)r=await cloud.auth.signUp({email,password});if(r.error){alert(r.error.message);return}localStorage.setItem('cloudEmail',email);const s=await cloud.auth.getSession();if(s.data.session){const q=await cloud.from('life_dashboard').select('data').eq('user_id',s.data.session.user.id).maybeSingle();if(q.data?.data){db=q.data.data;localStorage.setItem('myLifeDashboardFresh',JSON.stringify(db))}else await cloudSave()}render();toast('Cloud connected')}
async function logoutCloud(){if(cloud)await cloud.auth.signOut();localStorage.removeItem('cloudEmail');toast('Signed out');render()}
function notifications(){const n=db.deadlines.filter(d=>d.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,8);$('modalTitle').textContent='Upcoming notifications';$('form').innerHTML=(n.map(d=>'<div class="item"><b>'+esc(d.title)+'</b><div class="muted">'+fmt(d.date)+' • '+esc(d.time||'')+'</div></div>').join('')||'<div class="empty">No upcoming deadlines.</div>')+'<button type="button" class="btn primary" onclick="closeModal()">Close</button>';$('modal').classList.add('show')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('search').oninput=render;$('theme').onclick=toggleTheme;$('bell').onclick=notifications;setupNav();document.documentElement.dataset.theme=localStorage.getItem('theme')||'light';$('profileName').textContent=localStorage.getItem('profileName')||'Abraham Waar';$('avatar').textContent=($('profileName').textContent[0]||'A').toUpperCase();if(localStorage.getItem('sbUrl')&&localStorage.getItem('sbKey'))try{cloud=window.supabase.createClient(localStorage.getItem('sbUrl'),localStorage.getItem('sbKey'))}catch(e){}render();
