const AREAS=['University & Study','Career & Jobs','Businesses & Organisations','Programming & Digital Skills','Social Media & Content','Finance & Business Planning','Documents & Projects','Personal Development'];
const PAGES=['Dashboard','Today','Tasks','Goals','Calendar','Projects','Notes','Areas','Documents','Settings'];
const SEED={tasks:[
{id:1,title:'Complete Digital Systems assignment',area:'University & Study',priority:'High',status:'In Progress',due:'2026-10-03'},
{id:2,title:'Study Electromagnetic Theory',area:'University & Study',priority:'Medium',status:'Not Started',due:'2026-10-05'},
{id:3,title:'Update CV and job applications',area:'Career & Jobs',priority:'High',status:'Not Started',due:'2026-10-04'},
{id:4,title:'Plan SSYDIO monthly social media content',area:'Businesses & Organisations',priority:'Medium',status:'In Progress',due:'2026-10-06'},
{id:5,title:'Update KUOY AGRISOL LTD company profile',area:'Businesses & Organisations',priority:'High',status:'Not Started',due:'2026-10-08'},
{id:6,title:'Continue C++ learning',area:'Programming & Digital Skills',priority:'Medium',status:'In Progress',due:'2026-10-07'}],
goals:[
{id:1,title:'Build my personal productivity system',area:'Personal Development',target:'2026-12-31',progress:35,status:'Active'},
{id:2,title:'Develop SSYDIO programmes and content',area:'Businesses & Organisations',target:'2026-12-15',progress:25,status:'Active'},
{id:3,title:'Improve programming skills',area:'Programming & Digital Skills',target:'2026-12-31',progress:30,status:'Active'}],
projects:[
{id:1,title:'My Life Dashboard',area:'Programming & Digital Skills',status:'Active',priority:'High',progress:55,deadline:'2026-10-20',description:'Personal command center.'},
{id:2,title:'SSYDIO Development & Content Plan',area:'Businesses & Organisations',status:'Planning',priority:'High',progress:20,deadline:'2026-11-15',description:'Programmes, partnerships and content.'},
{id:3,title:'KUOY AGRISOL LTD Business Development',area:'Businesses & Organisations',status:'Planning',priority:'High',progress:15,deadline:'2026-12-01',description:'Documents, proposals and funding.'}],
deadlines:[
{id:1,title:'Digital Systems assignment',date:'2026-10-03',time:'10:00',area:'University & Study',priority:'High'},
{id:2,title:'Update CV and applications',date:'2026-10-04',time:'18:00',area:'Career & Jobs',priority:'Medium'},
{id:3,title:'SSYDIO content plan',date:'2026-10-06',time:'17:00',area:'Businesses & Organisations',priority:'High'}],
notes:[],documents:[]};
const cloneData=o=>JSON.parse(JSON.stringify(o));
let db=JSON.parse(localStorage.getItem('myLifeDashboardFresh')||'null')||cloneData(SEED),page='Dashboard',filter='all',cal=new Date(),cloud=null;
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—';
function save(){localStorage.setItem('myLifeDashboardFresh',JSON.stringify(db));if(cloud)cloudSave()}
function badge(v){return '<span class="pill '+(v==='Completed'?'ok':(v==='High'||v==='In Progress'?'warn':''))+'">'+esc(v)+'</span>'}
function setupNav(){PAGES.forEach(p=>{for(const id of ['nav','mobile']){const b=document.createElement('button');b.textContent=p;b.dataset.page=p;b.onclick=()=>go(p);$(id).appendChild(b)}})}
function go(p){page=p;$('title').textContent=p;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
function render(){const q=$('search').value.trim().toLowerCase();$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('view').innerHTML=q?searchPage(q):({Dashboard:dashboard,Today:todayPage,Tasks:tasksPage,Goals:goalsPage,Calendar:calendarPage,Projects:projectsPage,Notes:notesPage,Areas:areasPage,Documents:documentsPage,Settings:settingsPage}[page]())}
function dashboard(){const active=db.tasks.filter(t=>t.status!=='Completed').length,done=db.tasks.filter(t=>t.status==='Completed').length,over=db.tasks.filter(t=>t.due<today()&&t.status!=='Completed').length,due=db.tasks.filter(t=>t.due===today()&&t.status!=='Completed').length,avg=db.goals.length?Math.round(db.goals.reduce((a,g)=>a+Number(g.progress),0)/db.goals.length):0;return '<div class="grid stats">'+stat('Active tasks',active,'☑')+stat('Completed',done,'✓')+stat('Overdue',over,'!')+stat('Due today',due,'◷')+stat('Goal average',avg+'%','◎')+'</div><div class="section"><h2>Overview</h2><div class="tools"><button class="btn primary" onclick="openForm(\'task\')">+ Task</button><button class="btn" onclick="openForm(\'deadline\')">+ Deadline</button></div></div><div class="grid two"><div class="card"><h3>Task status</h3><div class="bars">'+bar('Done',done,Math.max(1,db.tasks.length))+bar('Active',active,Math.max(1,db.tasks.length))+'</div></div><div class="card"><h3>Goal progress</h3><div class="bars">'+db.goals.map(g=>bar(g.title,g.progress,100)).join('')+'</div></div></div><div class="section"><h2>Priority tasks</h2><button class="btn" onclick="go('Tasks')">View all</button></div><div class="card">'+db.tasks.filter(t=>t.status!=='Completed').slice(0,6).map(taskRow).join('')+'</div><div class="section"><h2>Upcoming deadlines</h2><button class="btn" onclick="go('Calendar')">Calendar</button></div><div class="card">'+db.deadlines.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6).map(d=>'<div class="item row"><div><b>'+esc(d.title)+'</b><div class="muted">'+fmt(d.date)+' • '+esc(d.time||'')+'</div></div>'+badge(d.priority)+'</div>').join('')+'</div>'}
function stat(a,b,c){return '<div class="card stat"><div><span class="muted">'+a+'</span><br><strong>'+b+'</strong></div>'+c+'</div>'}
function bar(label,value,max){return '<div class="barbox"><b>'+value+(max===100?'%':'')+'</b><div class="bar" style="height:'+Math.max(8,Math.min(170,value/max*170))+'px"></div><span>'+esc(label).slice(0,12)+'</span></div>'}
function taskRow(t){return '<div class="item row"><div><b>'+esc(t.title)+'</b><div class="muted">'+esc(t.area)+' • '+fmt(t.due)+' • '+esc(t.priority)+'</div></div><div class="tools"><button class="btn" onclick="toggleTask('+t.id+')">'+(t.status==='Completed'?'Reopen':'Done')+'</button><button class="btn" onclick="openForm(\'task\','+t.id+')">Edit</button></div></div>'}
function todayPage(){const a=db.tasks.filter(t=>t.due===today());return '<div class="card"><div class="section"><h2>Today</h2><button class="btn primary" onclick="openForm(\'task\')">+ Task</button></div>'+(a.map(taskRow).join('')||'<div class="empty">Nothing due today.</div>')+'</div>'}
function tasksPage(){const a=db.tasks.filter(t=>filter==='all'||(filter==='today'&&t.due===today())||(filter==='overdue'&&t.due<today()&&t.status!=='Completed')||(filter==='completed'&&t.status==='Completed'));return '<div class="section"><h2>Tasks</h2><div class="tools">'+['all','today','overdue','completed'].map(f=>'<button class="btn '+(filter===f?'primary':'')+'" onclick="filter=\''+f+'\';render()">'+f+'</button>').join('')+'<button class="btn primary" onclick="openForm(\'task\')">+ Add task</button></div></div><div class="kanban">'+['Not Started','In Progress','Completed'].map(s=>'<div class="col"><h3>'+s+'</h3><div ondragover="event.preventDefault()" ondrop="drop(event,\''+s+'\')">'+a.filter(t=>t.status===s).map(t=>'<div class="task" draggable="true" ondragstart="event.dataTransfer.setData(\'text/plain\','+t.id+')"><b>'+esc(t.title)+'</b><div class="muted">'+esc(t.area)+' • '+fmt(t.due)+'</div><br><button class="btn" onclick="openForm(\'task\','+t.id+')">Edit</button></div>').join('')+'</div></div>').join('')+'</div>'}
function drop(e,s){const t=db.tasks.find(x=>x.id===Number(e.dataTransfer.getData('text/plain')));if(t){t.status=s;save();render();toast('Task moved')}}
function toggleTask(id){const t=db.tasks.find(x=>x.id===id);if(t){t.status=t.status==='Completed'?'Not Started':'Completed';save();render();toast('Task updated')}}
function goalsPage(){return '<div class="section"><h2>Goals</h2><button class="btn primary" onclick="openForm(\'goal\')">+ Goal</button></div><div class="grid two">'+db.goals.map(g=>'<div class="card"><div class="row"><b>'+esc(g.title)+'</b>'+badge(g.status)+'</div><p class="muted">'+esc(g.area)+' • Target '+fmt(g.target)+'</p><div class="progress"><i style="width:'+g.progress+'%"></i></div><p><b>'+g.progress+'%</b></p><button class="btn" onclick="openForm(\'goal\','+g.id+')">Edit</button> <button class="btn danger" onclick="removeItem(\'goals\','+g.id+')">Delete</button></div>').join('')+'</div>'}
function calendarPage(){const y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<first;i++)cells+='<div class="day"></div>';for(let d=1;d<=days;d++){const iso=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),ev=db.deadlines.filter(x=>x.date===iso);cells+='<div class="day '+(iso===today()?'today':'')+'"><b>'+d+'</b>'+ev.map(x=>'<div class="event" onclick="openForm(\'deadline\','+x.id+')">'+esc(x.title)+'</div>').join('')+'</div>'}return '<div class="card"><div class="section"><button class="btn" onclick="cal.setMonth(cal.getMonth()-1);render()">‹</button><h2>'+cal.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</h2><div class="tools"><button class="btn" onclick="cal.setMonth(cal.getMonth()+1);render()">›</button><button class="btn primary" onclick="openForm(\'deadline\')">+ Deadline</button></div></div><div class="calendar">'+['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>'<div class="day"><b>'+x+'</b></div>').join('')+cells+'</div></div>'}
function projectsPage(){return '<div class="section"><h2>Projects</h2><button class="btn primary" onclick="openForm(\'project\')">+ Project</button></div><div class="grid two">'+db.projects.map(p=>'<div class="card"><div class="row"><b>'+esc(p.title)+'</b>'+badge(p.status)+'</div><p class="muted">'+esc(p.area)+' • '+esc(p.priority)+' • '+fmt(p.deadline)+'</p><div class="progress"><i style="width:'+p.progress+'%"></i></div><p><b>'+p.progress+'%</b></p><p class="muted">'+esc(p.description||'')+'</p><button class="btn" onclick="openForm(\'project\','+p.id+')">Edit</button> <button class="btn danger" onclick="removeItem(\'projects\','+p.id+')">Delete</button></div>').join('')+'</div>'}
function notesPage(){return '<div class="section"><h2>Notes</h2><button class="btn primary" onclick="openForm(\'note\')">+ Note</button></div><div class="grid two">'+(db.notes.map(n=>'<div class="card"><b>'+esc(n.title)+'</b><p>'+esc(n.content)+'</p><button class="btn" onclick="openForm(\'note\','+n.id+')">Edit</button> <button class="btn danger" onclick="removeItem(\'notes\','+n.id+')">Delete</button></div>').join('')||'<div class="card empty">No notes yet.</div>')+'</div>'}
function areasPage(){return '<div class="grid two">'+AREAS.map(a=>'<div class="card"><h3>'+esc(a)+'</h3><p class="muted">'+db.tasks.filter(x=>x.area===a).length+' tasks • '+db.goals.filter(x=>x.area===a).length+' goals • '+db.projects.filter(x=>x.area===a).length+' projects</p></div>').join('')+'</div>'}
function documentsPage(){return '<div class="section"><h2>Documents</h2><button class="btn primary" onclick="openForm(\'document\')">+ Document</button></div><div class="card">'+(db.documents.map(d=>'<div class="item row"><div><b>'+esc(d.title)+'</b><div class="muted">'+esc(d.type)+' • '+esc(d.area)+' • '+esc(d.status||'Planned')+'</div></div><button class="btn" onclick="openForm(\'document\','+d.id+')">Edit</button></div>').join('')||'<div class="empty">No documents tracked.</div>')+'</div>'}
function settingsPage(){return '<div class="grid two"><div class="card"><h2>Profile</h2><div class="field"><label>Name</label><input id="name" value="'+esc(localStorage.getItem('profileName')||'Abraham Waar')+'"></div><button class="btn primary" style="margin-top:10px" onclick="saveProfile()">Save profile</button></div><div class="card"><h2>Appearance</h2><button class="btn" onclick="toggleTheme()">Toggle dark mode</button></div><div class="card"><h2>Cloud Sync</h2><p class="muted">Optional Supabase sync across devices.</p><div class="field"><label>Project URL</label><input id="sbUrl" value="'+esc(localStorage.getItem('sbUrl')||'')+'" placeholder="https://...supabase.co"></div><div class="field"><label>Anon / publishable key</label><input id="sbKey" type="password" value="'+esc(localStorage.getItem('sbKey')||'')+'"></div><div class="tools" style="margin-top:10px"><button class="btn" onclick="configureCloud()">Save connection</button><button class="btn primary" onclick="loginCloud()">Sign in / Create account</button><button class="btn danger" onclick="logoutCloud()">Sign out</button></div></div><div class="card"><h2>Data</h2><button class="btn" onclick="exportData()">Export JSON</button> <button class="btn danger" onclick="resetData()">Reset fresh data</button></div></div>'}
function searchPage(q){let out=[];['tasks','goals','projects','notes','deadlines','documents'].forEach(k=>(db[k]||[]).forEach(x=>{if(JSON.stringify(x).toLowerCase().includes(q))out.push('<div class="item"><b>'+esc(x.title)+'</b><div class="muted">'+k+'</div></div>')}));return '<div class="card"><h2>Search results</h2>'+(out.join('')||'<div class="empty">No results.</div>')+'</div>'}
